### ISSUE TITLE
Latest zyxel firmware only allows private key auth

### ISSUE THREAD

**Issue by poshul** [xvzf/zyxel-gpon-sfp#18]
Ordered one of these last month. The version of the firmware it has disables password access to SSH, attempting to connect results in:
'Unable to negotiate with 10.10.1.1 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss"

**Comment by jaseg** [comment]
This error message happens because the firmware uses an sshd almost as old as time itself, which means your ssh client has to use an insecure *host* key type. Host keys are what ssh uses to authenticate hosts, not users. They are what gets stored in `~/.ssh/known_hosts` and what causes those "you are connecting here for the first time" messages, and are not the same as the keys used for user authentication (which most people think of when they talk about ssh keys).

You can fix this by telling your ssh client to downgrade its supported host key ciphers with:
`ssh -oHostKeyAlgorithms=+ssh-rsa ...` (see issue #14)

**Comment by poshul** [comment]
Ahh, thanks.
